version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkinsblueocean/compose
    build:
      context: .
    ports:
      - "2000:8080"
    volumes:
      - /home/jenkins/jenkins_wrk/volumes/jenkins_home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
networks:
  net:
